cook = [
    {
        "name": "VISITOR_PRIVACY_METADATA",
        "value": "CgJNRBIEGgAgaw%3D%3D",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1756410462,
        "storeId": None
    },
    {
        "name": "__Secure-3PSID",
        "value": "g.a000uQjV9ErBVyIbcsj-whaJjMdDAD5nY2wgpyNlkHRzO5EciWWD30TUYiMpjaP_pD6bTO93GAACgYKAXQSARQSFQHGX2MihDu_k1i7DyTGiaw2HOP5vRoVAUF8yKrgq5As5864TeKIkUx7UU5G0076",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "SIDCC",
        "value": "AKEyXzV8Ayvqf4SNfTUG__j16uQKj97n9JsWIf18ZpzV418E4EAijgAZIIfTwfhmYZZvpVyf",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": False,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1772394523,
        "storeId": None
    },
    {
        "name": "YSC",
        "value": "nm7ETrP-wE8",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": True,
        "firstPartyDomain": "",
        "partitionKey": None,
        "storeId": None
    },
    {
        "name": "SID",
        "value": "g.a000uQjV9ErBVyIbcsj-whaJjMdDAD5nY2wgpyNlkHRzO5EciWWDMzczJIm0b3KrKzEfdGx1BAACgYKARgSARQSFQHGX2MiwSS2nyTvVV8S8oLFz76YGxoVAUF8yKobFVKK3Qp-gBFXsYVx6bgG0076",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": False,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "__Secure-1PSIDTS",
        "value": "sidts-CjEBEJ3XVw-Tb8TjMEpOfou8TSyWVLVkgbeTBwYbAPxwACofdZTvdMmdjwucrRVgqBRxEAA",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1772394467,
        "storeId": None
    },
    {
        "name": "SAPISID",
        "value": "VzM9H-JzPfTxzlaD/AfW6EbQJ5VAxVkbCC",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "__Secure-1PSIDCC",
        "value": "AKEyXzUSVcazagqaebfQqp3nWXhHo4FHuEZhMqytIAv6U_51yyfnObE5UhalPaBwAsP5kw7DFg",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1772394523,
        "storeId": None
    },
    {
        "name": "SSID",
        "value": "AVyITEeZ7SNhMUpsk",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "__Secure-1PAPISID",
        "value": "VzM9H-JzPfTxzlaD/AfW6EbQJ5VAxVkbCC",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "__Secure-1PSID",
        "value": "g.a000uQjV9ErBVyIbcsj-whaJjMdDAD5nY2wgpyNlkHRzO5EciWWDHMgvOy-pVjQSL9cOoHqwagACgYKAUYSARQSFQHGX2Miqhi_x-GmgL8P51Q5XIVAQxoVAUF8yKrGhLpT8XZLFiZaGdLJ7KI20076",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "__Secure-3PAPISID",
        "value": "VzM9H-JzPfTxzlaD/AfW6EbQJ5VAxVkbCC",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "__Secure-3PSIDCC",
        "value": "AKEyXzW2VOo0qu8_KHl4bmUPHLfCDUDeX8f8-KjOruX0E-QCj3JQDyGqocn0T2g2NcTyO_my",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1772394523,
        "storeId": None
    },
    {
        "name": "__Secure-3PSIDTS",
        "value": "sidts-CjEBEJ3XVw-Tb8TjMEpOfou8TSyWVLVkgbeTBwYbAPxwACofdZTvdMmdjwucrRVgqBRxEAA",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1772394467,
        "storeId": None
    },
    {
        "name": "__Secure-ROLLOUT_TOKEN",
        "value": "CKLt1eKu8rO8dxCKxrTI-uGLAxjm2qOR0-mLAw%3D%3D",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1756410460,
        "storeId": None
    },
    {
        "name": "APISID",
        "value": "MlTnvw3ON30DUjGA/A6cAr7Nqch3YLq0NF",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": False,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "HSID",
        "value": "ALedg3yNKyDidlrdQ",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": False,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775161800,
        "storeId": None
    },
    {
        "name": "LOGIN_INFO",
        "value": "AFmmF2swRgIhAJzHLWBquWRAxDVuzNjCKiSOjDameDKAeNz6ILHHhZUJAiEAiElGGSlHXDD7bb8zJTrtoI6gXv0QdZS9h7bE1modMCg:QUQ3MjNmektEdzNjTGdCOGJwQjZoNjIyRDl2aUhENGFUOU96NTNjS0ozdWtGSEs4VXAtc3QtS0RSNkJLTWRGcFpHRkxZWVNPMFNHOFc0Z3BWdWZpMGlOclFsVzFmWURSdTdNRWxPZ3lRenVZWElyX1VYa0VkUHlpQmtxS1RUaEk4OEZPMTVqUXdleVZIUC15N2F4YktJUkdUcUU2YUM0TThR",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775418462,
        "storeId": None
    },
    {
        "name": "PREF",
        "value": "f4=4000000&f6=40000000&tz=Europe.Chisinau",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": False,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1775418465,
        "storeId": None
    },
    {
        "name": "VISITOR_INFO1_LIVE",
        "value": "mh8q9NH2M7M",
        "domain": ".youtube.com",
        "hostOnly": False,
        "path": "/",
        "secure": True,
        "httpOnly": True,
        "sameSite": "no_restriction",
        "session": False,
        "firstPartyDomain": "",
        "partitionKey": None,
        "expirationDate": 1756410462,
        "storeId": None
    }
]